### ISSUE TITLE
Couldn't load loot table levelup:digging/uncommon_dig

### ISSUE THREAD

**Issue by C0rn3j** [BeetoGuy/LevelUp#1]
http://pastebin.com/g3jU26QU

Server, forge 2095, LevelUp!-0.12.1-1.10.2.jar

**Comment by BeetoGuy** [comment]
Oh, right, I was going to release an update that got rid of that extra comma. Completely slipped my mind, sorry about that.

**Comment by C0rn3j** [comment]
Thanks a bunch!
