### ISSUE TITLE
Config for all ores to have the NoPlacing tag not working in latest version

### ISSUE THREAD

**Issue by thephoenixlodge** [BeetoGuy/LevelUp#11]
After it was initially added, this config option worked perfectly, but has at somepoint since stopped working, with the tag only being applied to ores doubled by the mining skill regardless of the state of this config option.

MC 1.10.2
LevelUp! 0.12.9
Forge 12.18.3.2254

**Comment by BeetoGuy** [comment]
Seems to work on my end. Maybe another mod's interfering with it?

**Comment by thephoenixlodge** [comment]
Hmmm, weird, I toggled the config off and then back on again and it's working perfectly now. Don't know quite what was going on there, but guess it's resolved for now
