### ISSUE TITLE
Can not compile 1.10.2 branch.

### ISSUE THREAD

**Issue by rewable** [BeetoGuy/LevelUp#15]
Latest state of "1.10.2" branch not compiling by command "gradlew build", however latest state of "master" branch compiling without problems.
This is gradle.log -> https://pastebin.com/raw/dj3MAxMJ

**Comment by BeetoGuy** [comment]
Yeah, that was before I started using the Maven for CraftTweaker. Let me see if I can update the build.gradle to use that.

**Comment by rewable** [comment]
Thanks for answer, but after this commit mod still ain't compiling with this log -> https://pastebin.com/raw/Fuc0ZP2K

**Comment by BeetoGuy** [comment]
Looks like the same issue. Might need to redo the setup before trying to build.

**Comment by rewable** [comment]
I've tried "gradlew setupCIWorkspace", it was build successfully, then "gradlew build", and this error again.

**Comment by BeetoGuy** [comment]
Only thing I can think of is to download the 1.10 CraftTweaker-Dev-Full file from [here](http://ci.blamejared.com/job/CraftTweaker-Dev/), put it into the libs directory, and comment out the Maven things in favor of compiling from that directory. I have no idea why it's giving you this much grief.
