### ISSUE TITLE
[Resource] es_ES/MX translation

### ISSUE THREAD

**Issue by Dorzar** [BeetoGuy/LevelUp#16]
//Traslated by: Dorzar / VeryHardChamp
//Última actualización: 23/07/2017
levelup.cost=Costo de nivel: %s
levelup.levels.track=Nivel actual: %s | Nivel original: %s
levelup.skill.increase=Aumentar
levelup.skill.decrease=Disminuir
levelup:mining_bonus.desc=EXP extra al minar.
levelup:craft_bonus.desc=EXP extra al fabricar objetos.
levelup:combat_bonus.desc=EXP extra al combatir.
levelup:woodcutting.desc=+ Eficiencia con el hacha.
levelup:lumbering.desc=+ Chance: x2 drop de troncos.
levelup:stonecutting.desc=+ Eficiencia con el pico.
levelup:prospecting.desc=+ Chance: x2 drop de minerales.
levelup:flintloot.desc=+ Chance: encontrar pedernal.
levelup:treasurehunting.desc=+ Chance: Obtener un objeto mientras excavas.
levelup:swordcrit.desc=+ Chance: Críticos al azar.
levelup:sworddamage.desc=+ Daño con los objetos.
levelup:bowdraw.desc=+ Velocidad de preparación.
levelup:arrowspeed.desc=+ Velocidad de flecha.
levelup:stealth.desc=- Rango de visión de los mobs mientras estás en sigilo.
levelup:stealthdamage.desc=+ Daño mientras estás en sigilo.
levelup:shieldblock.desc=+ Chance: bloquear el daño no bloqueable con escudos.
levelup:naturalarmor.desc=- Daño de los mobs.
levelup:cropgrowth.desc=+ Chance: cultivos cercanos crezcan
levelup:cropgrowth.desc.1=mucho más rápido.
levelup:harvestbonus.desc=+ Chance: x2 drop de cultivos.
levelup:sprintspeed.desc=+ Velocidad al esprintar.
levelup:fallprotect.desc=- Daño por caída.
levelup:stealthspeed.desc=+ Velocidad en sigilo.
levelup:furnacespeed.desc=+ Velocidad en los hornos.
levelup:furnacespeed.desc.1=SHIFT + Clic derecho con tu mano vacía para vincular un horno a ti.
levelup:furnacebonus.desc=+ Chance: x2 drop del horno.
levelup:brewingspeed.desc=+ Velocidad en el soporte para pociones.
levelup:brewingspeed.desc.1=SHIFT + Clic derecho con tu mano vacía para vincular un soporte de pociones a ti.
levelup:fishbonus.desc=+ Chance: x2 drop al pescar.

item.levelup:orechunk.name=Pedazo de %s
item.levelup:orechunk_null.name=Pedazo de mineral

skill.levelup:mining_bonus.short=Minería
skill.levelup:craft_bonus.short=Artesanía
skill.levelup:combat_bonus.short=Combate
skill.levelup:mining.desc=+ EXP al minar.
skill.levelup:craft.desc=+ EXP al fabricar.
skill.levelup:combat.desc=+ EXP al combatir.

skill.levelup:mining_bonus.name=Minero
skill.levelup:craft_bonus.name=Artesano
skill.levelup:combat_bonus.name=Guerrero
skill.levelup:stonecutting.name=Maestro del pico
skill.levelup:prospecting.name=Prospección
skill.levelup:woodcutting.name=Maestro del hacha
skill.levelup:lumbering.name=Tala de madera
skill.levelup:flintloot.name=Cosechador de pedernal
skill.levelup:treasurehunting.name=Cazador de tesoros
skill.levelup:swordcrit.name=Críticos al azar
skill.levelup:sworddamage.name=Daño de ataque
skill.levelup:bowdraw.name=Arquería
skill.levelup:arrowspeed.name=Velocidad de flecha
skill.levelup:stealth.name=Sigilo
skill.levelup:stealthdamage.name=Daño en sigilo
skill.levelup:shieldblock.name=Maestro del escudo
skill.levelup:naturalarmor.name=Piel de hierro
skill.levelup:cropgrowth.name=Maestro de los cultivos
skill.levelup:harvestbonus.name=Pulgar verde
skill.levelup:sprintspeed.name=Velocidad de esprintado
skill.levelup:fallprotect.name=Atletismo
skill.levelup:stealthspeed.name=Velocidad en sigilo
skill.levelup:furnacespeed.name=Maestro del horno
skill.levelup:furnacebonus.name=Eficiencia de la fundición
skill.levelup:brewingspeed.name=Hechicero
skill.levelup:fishbonus.name=Pescador

gui.levelup.skillmenu.0=Minería
gui.levelup.skillmenu.1=Artesanía
gui.levelup.skillmenu.2=Combate
gui.levelup.budget=Niveles gastados: %s
levelup.prereq=Requisitos previos: %s

levelup.interact.register=Máquina vinculada a %s
levelup.interact.unregister=Máquina desvinculada a %s
levelup.interact.notowned=La máquina ya está vinculada a %s

sneak.attack=¡Ataque en sigilo por %d de daño!
level.invalid=§e§l[Level Up!]§r§e Usted debe alcanzar el nivel 5 antes de elegir una especialización.§r

Enjoy it! you're welcome ^^

**Comment by BeetoGuy** [comment]
Thanks for the help!
