### ISSUE TITLE
Mining skill impacting digging speed, not mining speed?

### ISSUE THREAD

**Issue by Syndaryl** [BeetoGuy/LevelUp#6]
As per the topic...

I have 30 levels in mining and none in digging, I'm not seeing an improvement in speed using picks on stone, but I'm digging super-fast (not getting the digging bonus drops though).

Loving the mod overall, thanks for maintaining it!

**Comment by BeetoGuy** [comment]
Can I ask which Minecraft version this is? 1.10 or 1.11?

**Comment by Syndaryl** [comment]
My bad; 1.11.2 forge 13.20.0.2224

**Comment by BeetoGuy** [comment]
Well, it looks like it works right, but judging from the tests, the advantage is so slight that it just looks like it's slow. I'll try buffing the speed adjustment.

**Comment by Syndaryl** [comment]
Can you check whether I'm on crack about the shovel speed going up with Mining skill? On dirt, not on grass. Using a stone shovel it's like I'm using a diamond shovel with efficiency 3 or something, a single click and I explode two or three dirt blocks. But if I click on _grass_ it's just regular old diggery.

**Comment by BeetoGuy** [comment]
Yeah, I think I see what's going on with that.
